### ISSUE TITLE
WPF Head: Decimal point of culture?

### ISSUE THREAD

**Issue by ralfw** [ralfw/cashbook_incremental#11]
The decimal point for the amount indeed is a decimal point - even though I'm running the app on a German windows. Shouldn't it be a comma instead?

**Comment by CarstenKoenig** [comment]
see https://github.com/ralfw/cashbook_incremental/pull/12

**Comment by CarstenKoenig** [comment]
you can read a bit about the problem (and I shamelessly used the solution provided there) here: http://serialseb.blogspot.de/2007/04/wpf-tips-1-have-all-your-dates-times.html

**Comment by ralfw** [comment]
great it worked out. yeah, why not use the solution others have found?
and i'm so glad i don't have to deal with such intricacies :-)
