### ISSUE TITLE
WPF Head: Withdrawals should require a description to be entered

### ISSUE THREAD

**Issue by ralfw** [ralfw/cashbook_incremental#7]
Currently withdrawals like deposits don't require a descriptions. That's not according to requirements. (But it not yet checked for in the body.)

**Comment by CarstenKoenig** [comment]
Well it was in there but I feel like I should not touch this till someone has done the body part.

And if the body finally handles this the front end should already show an error message (in a `MessageBox`)

**Comment by ralfw** [comment]
I've done the body part :-) Indeed the head shows an error message.
Nevertheless, since this is a structural thing of the input data, I think it would be nice to have the head check in a way so that the withdrawal button is not enabled unless a description has been entered.

**Comment by CarstenKoenig** [comment]
please have a look at the comment I put on your last commit.

I don't want to reinvent your validation logic but right now there is no way on `IBody` to _validate_ inputs (but I think there should be)
